### ISSUE TITLE
Question: How can I add my own sounds

### ISSUE THREAD

**Issue by JustaFloatingEyeYT** [Lonk12/BetterDiscordPlugins#3]
I want to add my own sounds but I do not know where to put them.

**Comment by gugollo** [comment]
Came here to ask the exact same question ahahah

**Comment by Madasish** [comment]
This isnt a feature in the plugin. Or isnt yet at least.

**Comment by JustaFloatingEyeYT** [comment]
Ok, I was thinking I could put the audio somewhere in the files and edit the code, but does the audio come inside the plugin's file meaning I can't do that?

**Comment by Madasish** [comment]
It takes the mp3 files from the repo of the plugin.
https://github.com/Lonk12/BetterDiscordPlugins/tree/main/MemeSounds/Sounds
You can either edit the code to take the plugins from somewhere else (like
your own repo with all the reuploaded mp3s) or if your idea for a sound is
relevant enough i bet you could fork the repo, edit the code to add the mp3
file, upload the mp3 file and make a pull request.

piektd., 2022. g. 15. jūl., plkst. 20:52 — lietotājs Just a Floating Eye YT
***@***.***>) rakstīja:

**Comment by Orangenal-name** [comment]
Fork the repo, add your own sounds, make sure they are added in the plugin file as well, then create a pull request. I just did it in fact, check out the latest commit if you're unsure of how to add a sound into the plugin!

**Comment by Lonk12** [comment]
I might add the ability to add custom triggers and sounds eventually because it does sound like a good idea it's just idk how i would do that while keeping the amount of code as small as possible to ensure that there isn't any latency, on top of all that i would more consider me to be at a beginner level when it comes to JavaScript so I can't make any promises.
